name: GCC Build Check

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Compile with GCC
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GCC
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Compile project
        run: gcc -Wall -Werror -o program main.c
